#n = int(input('Digite um número para obter sua tabuada: '))
#print('-' * 18)
#print('A tabuada de {} é:'.format(n))
#print('1 x ', n, ' = ', n * 1)
#print('2 x ', n, ' = ', n * 2)
#print('3 x ', n, ' = ', n * 3)
#print('4 x ', n, ' = ', n * 4)
#print('5 x ', n, ' = ', n * 5)
#print('6 x ', n, ' = ', n * 6)
#print('7 x ', n, ' = ', n * 7)
#print('8 x ', n, ' = ', n * 8)
#print('9 x ', n, ' = ', n * 9)
#print('10 x ', n, ' = ', n * 10)
#print('-' * 18)

n = int(input('Digite um número para obter sua tabuada: '))
print('-' * 18)
print('A tabuada de {} é:'.format(n))
print('{} x {:2} = {}'.format(n, 1, n * 1))
print('{} x {:2} = {}'.format(n, 2, n * 2))
print('{} x {:2} = {}'.format(n, 3, n * 3))
print('{} x {:2} = {}'.format(n, 4, n * 4))
print('{} x {:2} = {}'.format(n, 5, n * 5))
print('{} x {:2} = {}'.format(n, 6, n * 6))
print('{} x {:2} = {}'.format(n, 7, n * 7))
print('{} x {:2} = {}'.format(n, 8, n * 8))
print('{} x {:2} = {}'.format(n, 9, n * 9))
print('{} x {:2} = {}'.format(n, 10, n * 10))
print('-' * 18)

#{:2} faz com que o número seja digitado um espaço à frente