n = int(input('Digite um número: '))
a = (n - 1)
s = (n + 1)
#print('O número digitado foi {}. Seu antecessor é {} e seu sucessor é {}.'.format(n, a, s))
#print('O número digitado foi {}. Seu antecessor é {} e seu sucessor é {}.'.format(n, n-1, n+1))
print(f'O número digitado foi {n}. Seu antecessor é {a} e seu sucessor é {s}')
