prim = int(input('Digite o primeiro termo: '))
raz = int(input('Digite a razão da PA: '))
termo = prim
cont = 1
total = 0
mais = 10
while mais != 0:
    total += mais
    while cont <= total:
        print('{} → '.format(termo), end='')
        termo += raz
        cont += 1
    mais = int(input('\nQuantos termos você quer mostrar a mais? '))
